sessionTimeoutInSeconds: 10

server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: iztl.keystore
      keyStorePassword: Th3_iztl_s3cr3t
      validateCerts: false
      validatePeers: false

database:
  driverClass: org.h2.Driver
  user: root
  password: r00t
  url: jdbc:h2:./target/h2db
